declare const Model: any;
import { Optional } from "sequelize";
export interface IOrder {
    id: number;
    order_serial_no?: string;
    order_mode?: string;
    token?: string;
    user_id: number;
    branch_id: number;
    subtotal: number;
    discount: number;
    delivery_charge: number;
    total_tax: number;
    total: number;
    order_type: number;
    order_date_time: Date;
    delivery_time?: Date;
    preparation_time?: number;
    is_advance_order: boolean;
    pos_received_amount?: number;
    pos_payment_method?: number;
    payment_status: string;
    status: string;
    dining_table_id?: number;
    delivery_boy_id?: number;
    reason?: string;
    source: number;
    creator_type?: string;
    creator_id?: number;
    editor_type?: string;
    editor_id?: number;
    createdAt?: Date;
    updatedAt?: Date;
}
type OrderCreationAttributes = Optional<IOrder, "id" | "order_serial_no" | "token" | "delivery_time" | "preparation_time" | "pos_received_amount" | "pos_payment_method" | "dining_table_id" | "delivery_boy_id" | "reason" | "creator_type" | "creator_id" | "editor_type" | "editor_id">;
declare class Order extends Model<IOrder, OrderCreationAttributes> implements IOrder {
    id: number;
    order_serial_no?: string;
    token?: string;
    user_id: number;
    branch_id: number;
    subtotal: number;
    discount: number;
    delivery_charge: number;
    total_tax: number;
    total: number;
    order_type: number;
    order_date_time: Date;
    delivery_time?: Date;
    preparation_time?: number;
    is_advance_order: boolean;
    pos_received_amount?: number;
    pos_payment_method?: number;
    payment_status: string;
    status: string;
    dining_table_id?: number;
    delivery_boy_id?: number;
    reason?: string;
    source: number;
    creator_type?: string;
    creator_id?: number;
    editor_type?: string;
    editor_id?: number;
    static associate(): void;
}
export default Order;
