declare const Model: any;
import { Optional } from "sequelize";
export interface IBranch {
    id: number;
    branch_virtual_id?: string;
    name: string;
    image?: string;
    email: string;
    phone: string;
    latitude?: number;
    longitude?: number;
    radius?: number;
    location?: string;
    address?: string;
    status: number;
    creator_type?: string;
    creator_id?: number;
    editor_type?: string;
    editor_id?: number;
    license_code?: string;
    branch_id?: string;
    password?: string;
    otp?: string;
    otp_expiry?: Date;
    role_id?: number;
    fcm_token?: string;
    createdAt?: Date;
    updatedAt?: Date;
    deletedAt?: Date;
}
type BranchCreationAttributes = Optional<IBranch, "id" | "status" | "creator_type" | "creator_id" | "editor_type" | "editor_id" | "createdAt" | "updatedAt" | "deletedAt">;
declare class Branch extends Model<IBranch, BranchCreationAttributes> implements IBranch {
    id: number;
    readonly branch_virtual_id: string;
    name: string;
    image?: string;
    email: string;
    phone: string;
    latitude?: number;
    longitude?: number;
    radius?: number;
    location?: string;
    address?: string;
    status: number;
    creator_type?: string;
    creator_id?: number;
    editor_type?: string;
    editor_id?: number;
    license_code?: string;
    branch_id?: string;
    password?: string;
    otp?: string;
    otp_expiry?: Date;
    role_id?: number;
    fcm_token?: string;
    readonly createdAt: Date;
    readonly updatedAt: Date;
    readonly deletedAt: Date;
}
export default Branch;
